FROM nginx:alpine

ADD ./data/nginx/default.conf /etc/nginx/conf.d/default.conf

# get env to nginx
CMD sh -c "envsubst \"`env | awk -F = '{printf \" \\\\$%s\", $1}'`\" < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
