version: '3'

services:
  flask-app:
    restart: always
    env_file: .env
    build:
      context: .
    ports:
      - "${FLASK_PUBLIC_PORT}:${FLASK_PUBLIC_PORT}"
    networks:
      - web_network
    volumes:
      - ${WORK_DIR:-.}/scripts:/scripts
    environment:
      FLASK_PUBLIC_PORT:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile-nginx
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - web_network
    depends_on: 
      - flask-app
    environment:
     FLASK_PUBLIC_PORT: 8000

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot



networks:
  web_network:
    driver: bridge
